[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
dependencies = [
    "pyDataverse==0.3.1",
    "pytest-selenium==2.0.1",
    "typer==0.3.2",
    'pydantic==1.8.2,extras=["dotenv"]'
]
