# Generated by Selenium IDE
from ..conftest import read_json


class TestUris:
    def test_uris(self, browsers):
        for driver in browsers:
            data = read_json("data.json")
            for r in data["resources"]:
                driver.get(r["uri"])
                if "title" in r:
                    assert r["title"] == driver.title
            driver.close()
