# Generated by Selenium IDE
import os
import time
import pytest
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from ..utils import read_json


class TestUris:
    def setup_method(self, method):
        firefox_options = Options()
        # firefox_options.headless = True
        self.driver = webdriver.Firefox(options=firefox_options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_uris(self):
        data = read_json("data.json")
        for r in data["resources"]:
            print(r)
            self.driver.get(r["uri"])
            if "title" in r:
                assert r["title"] == self.driver.title
        self.driver.close()
